# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class MarathonCloud < Formula
  desc "Command-line interface for Marathon Cloud"
  homepage "https://github.com/MarathonLabs/marathon-cloud-cli"
  version "0.1.0"
  license "MIT"

  on_macos do
    url "https://github.com/MarathonLabs/marathon-cloud-cli/releases/download/0.1.0/marathon-cloud_darwin_all-0.1.0.tar.gz"
    sha256 "22116503cd41c83afb68fee10e91a3b4deb174b32914119b88ee3a58ddc50b3e"

    def install
      bin.install "marathon-cloud"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/MarathonLabs/marathon-cloud-cli/releases/download/0.1.0/marathon-cloud_linux_arm_6-0.1.0.tar.gz"
      sha256 "edb54ea8ebeede768d63fa5b5d8ada2bb9128a01f07ccfa38f343810a376e3cd"

      def install
        bin.install "marathon-cloud"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/MarathonLabs/marathon-cloud-cli/releases/download/0.1.0/marathon-cloud_linux_amd64-0.1.0.tar.gz"
      sha256 "a3121a73eee6341f8dd95f7bfbf2a111fce6e7b87cd29f96e6e71d7f47c0fe23"

      def install
        bin.install "marathon-cloud"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/MarathonLabs/marathon-cloud-cli/releases/download/0.1.0/marathon-cloud_linux_arm64-0.1.0.tar.gz"
      sha256 "bd0e565c6005f5c36ec5bf47b589a3c57544caef58e83c44b7ceff5d50946a9c"

      def install
        bin.install "marathon-cloud"
      end
    end
  end
end
